// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package logsinput

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonBe7883f9DecodeGithubComWalklineIpcounterServingLogsinput(in *jlexer.Lexer, out *LogMsg) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "timestamp":
			out.Timestamp = string(in.String())
		case "ip":
			out.IP = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonBe7883f9EncodeGithubComWalklineIpcounterServingLogsinput(out *jwriter.Writer, in LogMsg) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"timestamp\":"
		out.RawString(prefix[1:])
		out.String(string(in.Timestamp))
	}
	{
		const prefix string = ",\"ip\":"
		out.RawString(prefix)
		out.String(string(in.IP))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v LogMsg) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonBe7883f9EncodeGithubComWalklineIpcounterServingLogsinput(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v LogMsg) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonBe7883f9EncodeGithubComWalklineIpcounterServingLogsinput(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *LogMsg) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonBe7883f9DecodeGithubComWalklineIpcounterServingLogsinput(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *LogMsg) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonBe7883f9DecodeGithubComWalklineIpcounterServingLogsinput(l, v)
}
